### ISSUE TITLE
Using the pre-trained model in Ubuntu !!!

### ISSUE THREAD

**Issue by madinwei** [lightning1010/3D-Face-Recognition#1]
Hello @lightning1010 , 
Thank you for this awesome code. I am trying to use this code with Ubuntu, however, loading the pre-trained model in ubuntu did not work I think for serialization of the model, and the pickle function does not support cross-platform. here is the error I got :
  
```
(3dfr) mad@mad:~/3D-Face-Recognition-master$ python predict.py --c configs/DTU3D-RGB.json --n assets/testmeshA.obj

Processing  assets/testmeshA.obj
Initialising model
Loading checkpoint
Getting device
Loading checkpoint: https://shapeml.compute.dtu.dk/Deep-MVLM/models/MVLMModel_DTU3D_RGB_07092019-c1cc3d59.pth
saved/trained/
Traceback (most recent call last):
  File "predict.py", line 74, in <module>
    main(global_config)
  File "predict.py", line 55, in main
    process_one_file(config, name)
  File "predict.py", line 12, in process_one_file
    dm = deepmvlm.DeepMVLM(config)
  File "/home/mad/3D-Face-Recognition-master/deepmvlm/api.py", line 38, in __init__
    self.device, self.model = self._get_device_and_load_model_from_url()
  File "/home/mad/3D-Face-Recognition-master/deepmvlm/api.py", line 76, in _get_device_and_load_model_from_url
    checkpoint = load_url(check_point_name, model_dir, map_location=device)
  File "/home/mad/miniconda3/envs/3dfr/lib/python3.7/site-packages/torch/hub.py", line 463, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/mad/miniconda3/envs/3dfr/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/mad/miniconda3/envs/3dfr/lib/python3.7/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/home/mad/miniconda3/envs/3dfr/lib/python3.7/pathlib.py", line 1030, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'WindowsPath' on your system

```
Is there a solution on how to load the pre-trained model or convert it to be able to load in Ubuntu?
Unfortunately, I need to use Ubuntu only for my project. 
thank you again and looking forward to your reply.

**Comment by madinwei** [comment]
a solution for the problem in [fix](https://github.com/fastai/fastai/issues/1482#issuecomment-798790974)
